apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echoenv
  name: echoenv
  namespace: echoenv
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echoenv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echoenv
    spec:
      containers:
      - image: quay.io/simonkrenger/echoenv:latest
        imagePullPolicy: Always
        name: echoenv
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
